apiVersion: apps/v1
kind: Deployment

metadata:
  name: unit-currency-converter

spec:
  replicas: 1

  selector:
    matchLabels:
      app: unit-currency-converter

  template:
    metadata:
      labels:
        app: unit-currency-converter

    spec:
      containers:
        - name: converter
          image: jayakumarv2629/unit-currency-converter:v1
          ports:
            - containerPort: 80